In [ ]:
import torch

In [ ]:
torch.__version__

'1.6.0+cu101'

In [ ]:
import numpy as np
lst=[3,4,5,6]

In [ ]:
arr=np.array(lst)
arr

array([3, 4, 5, 6])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
### Convert Numpy to Tensors

In [ ]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [ ]:
tensors.dtype

torch.int64

In [ ]:
### Indexing
tensors[:2]

tensor([3, 4])

In [ ]:
tensors[3]=100

In [ ]:
tensors

tensor([  3,   4,   5, 100])

In [ ]:
arr

array([  3,   4,   5, 100])

In [ ]:
### Disadvantage of from_numpy as both tensors and arr share same memory location 

In [ ]:
### Prevent this by using torch.tensor
tensors_arr=torch.tensor(arr)
tensors_arr

tensor([  3,   4,   5, 100])

In [ ]:
tensors_arr[3]=120
tensors_arr

tensor([  3,   4,   5, 120])

In [ ]:
arr

array([  3,   4,   5, 100])

In [ ]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [ ]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
### Arithmetic Operations:

In [ ]:
a=torch.tensor([3,4,5],dtype=torch.int32)
b=torch.tensor([4,5,6],dtype=torch.int32)
print(a+b)

tensor([ 7,  9, 11], dtype=torch.int32)


In [ ]:
torch.add(a,b)

tensor([ 7,  9, 11], dtype=torch.int32)

In [ ]:
c=torch.zeros(3)

In [ ]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [ ]:
torch.add(a,b).sum()

tensor(27)

In [ ]:
### Dot product and multiplication operations

In [ ]:
x=torch.tensor([3,4,5],dtype=torch.int32)
y=torch.tensor([4,5,6],dtype=torch.int32)

In [ ]:
x.mul(y)

tensor([12, 20, 30], dtype=torch.int32)

In [ ]:
x.dot(y)

tensor(62, dtype=torch.int32)

In [ ]:
### Matrix Multiplication:
x=torch.tensor([[3,4,5],[4,5,6]],dtype=torch.int32)
t=torch.tensor([[4,5],[6,7],[8,9]],dtype=torch.int32)
x@t

tensor([[ 76,  88],
        [ 94, 109]], dtype=torch.int32)

In [ ]:
torch.matmul(x,t)

tensor([[ 76,  88],
        [ 94, 109]], dtype=torch.int32)

In [ ]:
torch.mm(x,t)

tensor([[ 76,  88],
        [ 94, 109]], dtype=torch.int32)